#! /bin/bash -ex

# Build script for Varnish el7 RPM
# to be run in the rpmbuild/centos7 docker container.

# Env variables VERSION and RELEASE MUST be set in the docker invocation.
# DIST is set by the rpmbuild/centos7 container.

# The directory mounted to /srv MUST be the root directory of the
# pkg-varnish-cache repository.
# The Varnish tarball MUST be in the sources/ subdirectory.

# At the end of the run, binary, source and debuginfo RPMs are in the
# directory mounted to /srv.

if [ -z $VERSION ]; then
   echo "Env variable VERSION MUST be set"
   exit 1
fi

if [ -z $RELEASE ]; then
   echo "Env variable RELEASE MUST be set"
   exit 1
fi

# delete the peculiar macros from the rpmbuild/centos7 image
rm /home/builder/.rpmmacros

# set up the build environment
cd /home/builder
mkdir -p rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
cp /srv/redhat/varnish.spec rpmbuild/SPECS
cp /srv/redhat/* rpmbuild/SOURCES
rm rpmbuild/SOURCES/varnish.spec
cp /srv/sources/varnish-${VERSION}.tar.gz rpmbuild/SOURCES/varnish-${VERSION}.tgz

# from pkg-varnish-cache
sed -i -e "s/^Version:.*/Version: $VERSION/" rpmbuild/SPECS/varnish.spec
sed -i -e "s/.*define v_rc.*/\%define v_rc/" rpmbuild/SPECS/varnish.spec
sed -i -e 's/^make check/# make check/' rpmbuild/SPECS/varnish.spec

# update the build env
set +e
sudo yum check-update -y -q
set -e
sudo yum upgrade -y -q

# install epel7 repo
sudo yum install -y -q \
     https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

# build requirements
sudo yum install -y -q \
     diffutils gcc jemalloc-devel libedit-devel make ncurses-devel \
     pcre-devel pcre2-devel pkgconfig python3 python3-sphinx systemd-units

# build RPMs
rpmbuild -ba -D "dist .${DIST}" \
         -D "_smp_mflags -j10" \
         -D "releasetag ${RELEASE}" \
         -D "srcname varnish-${VERSION}" \
         rpmbuild/SPECS/varnish.spec

sudo cp rpmbuild/RPMS/*/* /srv
sudo cp rpmbuild/SRPMS/* /srv
